Vagrant.configure("2") do |config|
  # Windows Server 2016 Standard
  # Packer source https://github.com/gusztavvargadr/packer
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.box_version = "1607.0.2010"
  
  config.vm.guest = :windows
  config.vm.communicator == :winrm
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  config.vm.network "private_network", ip: "192.168.53.195"
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm_http", auto_correct: true
  config.vm.network :forwarded_port, guest: 5986, host: 5986, id: "winrm_https", auto_correct: true

  config.vm.provision "shell", path: "scripts/RMMemoryHotfix.ps1"
  config.vm.provision "shell", path: "scripts/ConfigureRM.ps1"
  config.vm.provision "shell", path: "scripts/InstallFMEDesktop.cmd", privileged: true, env: {"FME_LICENSING_SERVER" => ENV['FME_LICENSING_SERVER'], "FME_EDITION_NAME" => ENV['FME_EDITION_NAME']}

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5000"
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
end
